channels:
  targets:
    - [guyer, main]
travis:
  secure:
    BINSTAR_TOKEN: PVLuX9k3nlGB80TOnCM6mLL1xRsaBvJXtooBq3CFxFDXyayS2b7CQ4fgqTC7TYc+B3cVE+8jJzAXVXBiP1pFqgkqKLF4A3Sy9hnKcAO6BbISb2H/sufsdXCtEEV/61FNdX3yBEYQseiPqmGgMAZS/mDT9p3C25SD5+wG81EQDtwVcgQ/oXwWF9hvlplbi99FvOreIez+RCvHSwX5GF239ztuBCiKy1pR3IeoT7/ylQSJu7shzBFcCeEyE9tRAljWLkX7ALMPS20UcWcd1hOC7idWA1LkopdqohQdXoWcLUQ56/FkZAKxFqoKZxJDo2UDTHsGiy+uFYWVWkIldwRO47JMc+kmc8Cw2isWAMR4gM+gas9hgb7WKXHi0gwQYmnRh+98ipVfYIoGLoBv/3sxDs3PGjtBFqndJWoJIDSQ+0hM+XilYioWYPVUwIpqwuj2TUBTMc1rijkkH/WvvBZrvqqbmFaxNi9yui4D4/SvYodN339mbdtBz6EtqUDxSwp1/g+qPRrcAXRbU+uSQCCQKcaCArDxRm0af5FJ3TRgUDqeFXBiEtVdgWPwRLQdbBa6Ehji42OhXMaZyLh8jRv3v4AGVPUVc6j2BoGcYL4lm1adBHaUcwTUbFfi7MH8f4F0oBtfeFVZpDuFx6ZnNUmA4yamhQVvwFIfavkMQ0Ytctw=
appveyor:
  secure:
    BINSTAR_TOKEN: X89+MTZivHBAXLSEy/G8CnQu+orYtiX/vKbQ7w7Wqbhv11U+EPgW+otnBaeJ6JCY
