channels:
  targets:
  - [guyer, main]

travis:
  secure:
    BINSTAR_TOKEN: PmJquDbUnl7J7dDygVJ4PcdcMeJjoerfjX3o43b4qiarnj//OSVXuSx3Sqib8tZCCdLruTykYVZZnpbiJnLLxAl1MSpRgnumZLgxUa3Yrv5dYfxJj/pGu4C6h1v6MpIEjzRgzyf3fYNbBMcf12wA4mUJHM2pLj9nhg9fNE993Fkxz1wtLOF75334dZ+gEL3Aa/slnIK4rw9CFxW24+QXVWT6bHyuCxmKfouR34MTKNF112pilEB0CmOq4toSNrIqTjLvcedF5HviMGUPDi37qblgOiwFKisvKQ2msOMduSqO4n/Kzl8a8Rr/MQaV9+Jr8M3beCr8zWsZ1JQ7SirR+4/BaEt3SdnMEvvGL9/AWav2Jg8RWYQW5zjBFGgvfYQmW5jphvF4qoDOs2WPYTcmB+vizKbOVaHR7NEX25BiTblRJd8Adr/7ckRPb8MF9svZFWBiKYlaNNigvU5nUmtKVf13edlp+IcHzy3aSY+tdQZ8NUPCDdDzBu1Jyg31vV0GYRbc6xS+PIe8hMsA361OvVko8ZzXYP6g48reRAnq/iE+zeqGuyIOwGieO4bsCQOGDdNSceChCHFEx68kOzmckrmtIcZIF53t6P95gQl67tWSsrJ/OQMwM3Xu/KMOUeb8YoIbZu/+g9WIlO87qb9yp0QmzmHwQAZ7aaxM87GXM50=
appveyor:
  secure:
    BINSTAR_TOKEN: 26P3JkJ/iVPaW6c+5V5XYJ6H9Jaw/iYr0SU7KqDJCRk2+ScBP0rsvIyDOxDE9let
